import {movingAveragePath} from './moving-average.js?v=0b2e40405ee7fcd62ef27e0e253be40d5f854740-23f2a20b7717';
import {showMangaPortrait} from './manga-portraits.js?v=0b2e40405ee7fcd62ef27e0e253be40d5f854740-23f2a20b7717';
import {buildCurveScale} from './share-card.js?v=0b2e40405ee7fcd62ef27e0e253be40d5f854740-23f2a20b7717';
import {recapChoices,recapIntensity} from './daily-recap.js?v=0b2e40405ee7fcd62ef27e0e253be40d5f854740-23f2a20b7717';
import {createRecapPlayer} from './recap-player.js?v=0b2e40405ee7fcd62ef27e0e253be40d5f854740-23f2a20b7717';
import {formatTradingTime,timeAxisTicks} from './trading-time.js?v=0b2e40405ee7fcd62ef27e0e253be40d5f854740-23f2a20b7717';
const money=n=>(n<0?'−':'')+'¥'+Math.abs(n).toLocaleString('zh-CN',{maximumFractionDigits:2});
const signed=n=>(n>0?'+':'')+money(n);
const pct=n=>n===null?'—':(n>0?'+':'')+(n*100).toFixed(2)+'%';
const el=(doc,tag,cls,text)=>{const e=doc.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
const svgEl=(doc,tag,attrs={})=>{const e=doc.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;};
export function drawRecapCurve(doc,points,{label='资金曲线',partial=false,basis=null}={}){
 const chart=svgEl(doc,'svg',{viewBox:'0 0 620 215',role:'img','aria-label':label+'；纵轴日元，横轴游戏交易时间 JST'}),left=92,right=600,top=20,bottom=166;
 const series=points.filter(p=>Number.isFinite(p.nominalAssets)),values=series.flatMap(p=>[p.nominalAssets,...(basis!=='trading'&&Number.isFinite(p.netAssets)?[p.netAssets]:[])]),scale=buildCurveScale(values);
 const start=series[0]?.timestamp||0,range=Math.max(1,(series.at(-1)?.timestamp||start)-start),x=p=>left+(p.timestamp-start)/range*(right-left),y=v=>bottom-(v-scale.min)/(scale.max-scale.min)*(bottom-top);
 for(const value of scale.ticks){const Y=y(value),line=svgEl(doc,'line',{x1:left,x2:right,y1:Y,y2:Y,stroke:'#ddcbd7','stroke-dasharray':'3 4'});chart.append(line);const text=svgEl(doc,'text',{x:left-7,y:Y+4,'text-anchor':'end','font-size':11,fill:'#755e70'});text.textContent=money(value);chart.append(text);}
 for(const [key,color,dash]of (basis==='trading'?[['nominalAssets','#be417c','']]:[['nominalAssets','#be417c',''],['netAssets','#326c84','5 4']])){const ps=series.filter(p=>Number.isFinite(p[key]));if(ps.length){const line=svgEl(doc,'polyline',{points:ps.map(p=>`${x(p)},${y(p[key])}`).join(' '),fill:'none',stroke:color,'stroke-width':2.5,'stroke-dasharray':dash});chart.append(line);}}
 for(const p of series){const dot=svgEl(doc,'circle',{cx:x(p),cy:y(p.nominalAssets),r:4,fill:'#be417c',tabindex:0}),title=svgEl(doc,'title');title.textContent=`${formatTradingTime(p.timestamp,{full:true})}；${basis==='trading'?'交易资产':'名义资产'} ${money(p.nominalAssets)}${basis!=='trading'&&Number.isFinite(p.netAssets)?'；扣债净资产 '+money(p.netAssets):''}`;dot.setAttribute('aria-label',title.textContent);dot.append(title);chart.append(dot);}
 for(const t of timeAxisTicks(series,{maxTicks:4})){const text=svgEl(doc,'text',{x:x(t),y:188,'text-anchor':t.index===0?'start':t.index===series.length-1?'end':'middle','font-size':11,fill:'#755e70'});text.textContent=t.label;chart.append(text);}
 const caption=svgEl(doc,'text',{x:left,y:210,'font-size':11,fill:'#755e70'});caption.textContent=partial?'部分历史未记录，仅展示已知点；连线不代表完整盘中路径':basis==='trading'?'交易资产（剔除借还与消费） · 日元 / JST':'名义资产（粉） / 扣债净资产（蓝虚线） · 日元 / JST';chart.append(caption);return chart;
}
function candleReplay(doc,candles,averages=[]){
 const box=el(doc,'div','recap-candles');if(!candles.length){box.textContent='今天未生成 K 线，按实际早收结果结算。';return box;}
 const svg=svgEl(doc,'svg',{viewBox:'0 0 620 110',role:'img','aria-label':'今日已发生K线回放，横轴游戏时间 JST'}),lo=Math.min(...candles.map(c=>c.low),...averages.flatMap(a=>a.values.filter(Number.isFinite))),hi=Math.max(...candles.map(c=>c.high),...averages.flatMap(a=>a.values.filter(Number.isFinite))),spread=Math.max(.01,hi-lo),y=v=>12+(hi-v)/spread*62;
 candles.forEach((c,i)=>{const group=svgEl(doc,'g',{'data-recap-candle':i}),x=20+i/Math.max(1,candles.length-1)*580,color=c.close>=c.open?'#248b68':'#bc4276';group.append(svgEl(doc,'line',{x1:x,x2:x,y1:y(c.high),y2:y(c.low),stroke:color}),svgEl(doc,'rect',{x:x-4,y:Math.min(y(c.open),y(c.close)),width:8,height:Math.max(2,Math.abs(y(c.open)-y(c.close))),fill:color}));const title=svgEl(doc,'title');title.textContent=formatTradingTime(c.timestamp,{full:true});group.append(title);svg.append(group);});
 const maLegend=el(doc,'div','recap-ma-legend');for(const average of averages){const color=({5:'#92630d',10:'#137488',20:'#8054ac'})[average.period]||average.color,path=svgEl(doc,'path',{d:movingAveragePath(average.values,{x:i=>20+i/Math.max(1,candles.length-1)*580,y}),fill:'none',stroke:color,'stroke-width':1.5,'data-recap-ma':average.period}),button=el(doc,'button','',`MA${average.period} ${average.latest===null?'—':average.latest.toFixed(3)}`);button.type='button';button.style.color=color;button.setAttribute('aria-pressed','true');button.onclick=()=>{const on=button.getAttribute('aria-pressed')!=='true';button.setAttribute('aria-pressed',String(on));path.style.display=on?'':'none';};maLegend.append(button);svg.append(path);}box.append(maLegend);
 for(const t of timeAxisTicks(candles,{maxTicks:4})){const text=svgEl(doc,'text',{x:20+t.index/Math.max(1,candles.length-1)*580,y:102,'font-size':11,'text-anchor':t.index===0?'start':t.index===candles.length-1?'end':'middle',fill:'#755e70'});text.textContent=t.label;svg.append(text);}box.append(svg);return box;
}
export function mountDailyRecap(container,snapshot,{motion=true,reducedMotion=false,onSound=()=>{},onChoice=()=>{},cash=0,loanUnlocked=false,loanTerms=null,usedChoices=[],usedGroups=[],portraitUrl='',portraitPanel=null,moodLabel='今日心情'}={}){
 const doc=container.ownerDocument;container.replaceChildren();container.className='daily-recap';container.dataset.direction=snapshot.primary.profit>0?'profit':snapshot.primary.profit<0?'loss':'flat';container.style.setProperty('--recap-intensity',recapIntensity(snapshot));
 const heading=el(doc,'div','recap-heading'),primary=el(doc,'div','recap-primary');primary.append(el(doc,'span','recap-label',snapshot.primary.label),el(doc,'strong','recap-profit',signed(snapshot.primary.profit)),el(doc,'b','recap-rate',pct(snapshot.primary.returnRate)));if(portraitUrl){const image=el(doc,'img','recap-portrait');image.src=portraitUrl;image.alt=moodLabel;if(portraitPanel){const frame=el(doc,'div','recap-portrait-frame');frame.append(image);showMangaPortrait(image,portraitPanel);heading.append(frame);}else heading.append(image);}heading.append(primary);container.append(heading);
 const total=el(doc,'p','recap-cumulative',`累计已实现交易 ${signed(snapshot.cumulative.realizedProfit)} · ${pct(snapshot.cumulative.returnRate)}`);container.append(total);
 const stats=el(doc,'dl','recap-stats');for(const [label,value]of [['账户总资产',money(snapshot.account.nominalAssets)],['扣债净资产',money(snapshot.account.netAssets)],['未还债务',money(snapshot.account.debt)]]){stats.append(el(doc,'dt','',label),el(doc,'dd','',value));}container.append(stats);
 if(snapshot.note&&snapshot.curves.basis!=='trading')container.append(el(doc,'p','recap-note',snapshot.note));
 const playback=el(doc,'section','recap-playback'),running=el(doc,'strong','recap-counter',money(snapshot.daily.openingNominal)),step=el(doc,'span','recap-step','开盘交易资产'),skip=el(doc,'button','recap-skip','跳过动画');skip.type='button';playback.append(step,running,skip);const candles=candleReplay(doc,snapshot.candles,snapshot.candleMovingAverages||[]);playback.append(candles);container.append(playback);
 const tabs=el(doc,'div','recap-tabs'),curve=el(doc,'div','recap-curve');for(const [scope,label]of [['today',snapshot.curves.basis==='trading'?'今日交易资产曲线':'今日资金曲线'],['cumulative',snapshot.curves.basis==='trading'?'累计交易资产曲线':'累计资金曲线']]){const b=el(doc,'button','',label);b.type='button';b.onclick=()=>{for(const child of tabs.children)child.setAttribute('aria-pressed',String(child===b));curve.replaceChildren(drawRecapCurve(doc,snapshot.curves[scope],{label,partial:snapshot.curves[scope+'Partial'],basis:snapshot.curves.basis}));};tabs.append(b);}container.append(tabs,curve);tabs.firstElementChild.click();
 container.append(el(doc,'p','recap-clock',snapshot.timeNotice));const basis=el(doc,'details','recap-basis');basis.append(el(doc,'summary','','收益率和资金口径'),el(doc,'p','',snapshot.daily.returnBasis),el(doc,'p','',snapshot.cumulative.returnBasis),el(doc,'p','','名义资产包含借入资金；扣债净资产减去未还本金及未付利息。'));container.append(basis);
 const choiceBox=el(doc,'div','recap-choices');for(const choice of recapChoices(snapshot,{cash,loanUnlocked,loanTerms})){const b=el(doc,'button',choice.loan?'recap-loan':'recap-choice');b.type='button';b.disabled=!choice.enabled||usedChoices.includes(choice.id)||!!choice.group&&usedGroups.includes(choice.group);b.append(el(doc,'b','',choice.label+(choice.cost?` · ${money(choice.cost)}`:'')),el(doc,'small','',usedChoices.includes(choice.id)?'今天已选择':choice.group&&usedGroups.includes(choice.group)?'今晚已选过同类活动':choice.copy));b.title=choice.origin;b.onclick=()=>onChoice(choice);choiceBox.append(b);}if(choiceBox.children.length){container.append(el(doc,'p','recap-choice-hint','今晚怎么过？'),choiceBox);}
 let player=createRecapPlayer(snapshot,{enabled:motion,reducedMotion,render:f=>{running.textContent=money(f.value);step.textContent=f.segment.label;skip.hidden=f.complete;playback.dataset.complete=String(f.complete);container.dataset.animate=String(motion&&!reducedMotion&&!f.complete);for(const c of candles.querySelectorAll('[data-recap-candle]'))c.style.opacity=Number(c.dataset.recapCandle)<f.candleCount?'1':'.12';},onCue:({segment,intensity,rate})=>onSound(segment.delta>=0?'gain':'exhaust',{rate,level:.25+intensity*.3})});skip.onclick=()=>player.finish();return{snapshot,finish:()=>player.finish(),dispose:()=>player.cancel()};
}
